function saveFig(fig, subject, experimentName, figName, folderName)
    fileName = sprintf('%s%s%s%s', string(subject.name), '_', ...
        string(experimentName), figName);
    saveas(fig, ...
        fullfile(folderName, strcat(fileName, '.png')));
    saveas(fig, ...
        fullfile(folderName, 'TIF', strcat(fileName, '.tif')));
end